---

user: pwernicki

generic_software:
  - gpg
  - curl
  - wget
  - bash-completion
  - fortune-mod
  - ca-certificates
  - stow
  - fish
  - kitty
  - exa
  - timeshift

devops_software:
  - neovim
  - gcc
  - gcc-c++
  - nodejs
  - git
  - ansible
  - ansible-lint
  - terraform
  - terraform-ls
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

npm_software:
  - neovim
  - pyright
