---

- name: "Change shell to fish"
  ansible.builtin.command:
    cmd: "usermod -s /usr/bin/fish {{ user }}"
  changed_when: false
  become: true

- name: "Install fisher"
  ansible.builtin.shell:
    cmd: 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
  args:
    executable: /usr/bin/fish
  changed_when: false

- name: "Install tide"
  ansible.builtin.shell:
    cmd: 'fisher install IlanCosman/tide@v5'
  args:
    executable: /usr/bin/fish
  changed_when: false

- name: "Download Nerd fonts"
  ansible.builtin.git:
    repo: https://github.com/IlanCosman/tide.git
    dest: "/home/{{ user }}/tide"
    version: assets

- name: "Copy fonts"
  ansible.builtin.copy:
    src: "/home/{{ user }}/tide/fonts/"
    dest: "/home/{{ user }}/.fonts"
    mode: '0750'

- name: "Delete fonts git directory"
  ansible.builtin.file:
    path: "/home/{{ user }}/tide"
    state: absent
