---

- name: "Configure DNF"
  ansible.builtin.lineinfile:
    state: present
    path: /etc/dnf/dnf.conf
    line: "{{ item }}"
  loop:
    - gpgcheck=1
    - installonly_limit=3
    - clean_requirements_on_remove=True
    - best=False
    - skip_if_unavailable=True
    - max_parallel_downloads=10
  become: true

- name: "Import generic software"
  ansible.builtin.import_tasks: generic_software.yml
  tags: generic
  become: true

- name: "Import devops software"
  ansible.builtin.import_tasks: devops_software.yml
  tags: devops
  become: true

- name: "Import dotfiles"
  ansible.builtin.import_tasks: dotfiles.yml
  tags: dotfiles

- name: "Import fish extras"
  ansible.builtin.import_tasks: fish_extras.yml
  tags: fish

- name: "Import media"
  ansible.builtin.import_tasks: media.yml
  tags: media
  become: true

- name: "Import optimizations"
  ansible.builtin.import_tasks: optimizations.yml
  tags: optimizations
  become: true
