---

- name: Switch to full FFMPEG
  ansible.builtin.command:
    cmd: dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing
  changed_when: false

- name: Install the 'Multimedia' package group
  ansible.builtin.dnf:
    name: '@multimedia'
    state: present

- name: Update the 'Multimedia' package group
  ansible.builtin.dnf:
    name: '@multimedia'
    state: present
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin

- name: Update the 'sound-and-video' package group
  ansible.builtin.dnf:
    name: '@sound-and-video'
    state: present

- name: Install video decoding packages
  ansible.builtin.dnf:
    name: "{item}"
    state: present
  loop:
    - ffmpeg
    - ffmpeg-libs
    - libva
    - libva-utils

- name: Enable OpenH264 for Firefox
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled fedora-cisco-openh264
  changed_when: false

- name: Install OpenH264 for Firefox
  ansible.builtin.dnf:
    name: "{item}"
    state: present
  loop:
    - openh264
    - gstreamer1-plugin-openh264
    - mozilla-openh264
